// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: discovery.proto

package com.polytech.spik.protocol;

public final class DiscoveryMessages {
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DiscoveryMessage_descriptor;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DiscoveryRequest_descriptor;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DiscoveryResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DiscoveryMessage_fieldAccessorTable;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DiscoveryRequest_fieldAccessorTable;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DiscoveryResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n\017discovery.proto\"h\n\020DiscoveryMessage\022$\n" +
      "\007request\030\001 \001(\0132\021.DiscoveryRequestH\000\022&\n\010r" +
      "esponse\030\002 \001(\0132\022.DiscoveryResponseH\000B\006\n\004t" +
      "ype\"w\n\020DiscoveryRequest\022\014\n\004name\030\001 \002(\t\022\034\n" +
      "\002os\030\002 \002(\0162\020.OperatingSystem\022\024\n\014manufactu" +
      "rer\030\003 \002(\t\022\r\n\005model\030\004 \002(\t\022\022\n\nsdkVersion\030\005" +
      " \002(\005\"^\n\021DiscoveryResponse\022\014\n\004name\030\001 \002(\t\022" +
      "\034\n\002os\030\002 \002(\0162\020.OperatingSystem\022\017\n\007version" +
      "\030\003 \002(\t\022\014\n\004port\030\004 \002(\005*A\n\017OperatingSystem\022" +
      "\013\n\007WINDOWS\020\001\022\t\n\005MACOS\020\002\022\t\n\005LINUX\020\003\022\013\n\007AN",
      "DROID\020\004B/\n\032com.polytech.spik.protocolB\021D" +
      "iscoveryMessages"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_DiscoveryMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DiscoveryMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DiscoveryMessage_descriptor,
        new java.lang.String[] { "Request", "Response", "Type", });
    internal_static_DiscoveryRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DiscoveryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DiscoveryRequest_descriptor,
        new java.lang.String[] { "Name", "Os", "Manufacturer", "Model", "SdkVersion", });
    internal_static_DiscoveryResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_DiscoveryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DiscoveryResponse_descriptor,
        new java.lang.String[] { "Name", "Os", "Version", "Port", });
  }
  private DiscoveryMessages() {}

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  /**
   * Protobuf enum {@code OperatingSystem}
   */
  public enum OperatingSystem
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>WINDOWS = 1;</code>
     */
    WINDOWS(0, 1),
    /**
     * <code>MACOS = 2;</code>
     */
    MACOS(1, 2),
    /**
     * <code>LINUX = 3;</code>
     */
    LINUX(2, 3),
    /**
     * <code>ANDROID = 4;</code>
     */
    ANDROID(3, 4),
    ;

    /**
     * <code>WINDOWS = 1;</code>
     */
    public static final int WINDOWS_VALUE = 1;
    /**
     * <code>MACOS = 2;</code>
     */
    public static final int MACOS_VALUE = 2;
    /**
     * <code>LINUX = 3;</code>
     */
    public static final int LINUX_VALUE = 3;
    /**
     * <code>ANDROID = 4;</code>
     */
    public static final int ANDROID_VALUE = 4;
    private static final OperatingSystem[] VALUES = values();
    private static com.google.protobuf.Internal.EnumLiteMap<OperatingSystem>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<OperatingSystem>() {
            public OperatingSystem findValueByNumber(int number) {
              return OperatingSystem.valueOf(number);
            }
          };
    private final int index;
    private final int value;

    private OperatingSystem(int index, int value) {
      this.index = index;
      this.value = value;
    }

    public static OperatingSystem valueOf(int value) {
      switch (value) {
        case 1: return WINDOWS;
        case 2: return MACOS;
        case 3: return LINUX;
        case 4: return ANDROID;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<OperatingSystem>
        internalGetValueMap() {
      return internalValueMap;
    }

    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.polytech.spik.protocol.DiscoveryMessages.getDescriptor().getEnumTypes().get(0);
    }

    public static OperatingSystem valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    public final int getNumber() { return value; }

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }

    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    // @@protoc_insertion_point(enum_scope:OperatingSystem)
  }
  public interface DiscoveryMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DiscoveryMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .DiscoveryRequest request = 1;</code>
     */
    boolean hasRequest();
    /**
     * <code>optional .DiscoveryRequest request = 1;</code>
     */
    com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest getRequest();
    /**
     * <code>optional .DiscoveryRequest request = 1;</code>
     */
    com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequestOrBuilder getRequestOrBuilder();

    /**
     * <code>optional .DiscoveryResponse response = 2;</code>
     */
    boolean hasResponse();
    /**
     * <code>optional .DiscoveryResponse response = 2;</code>
     */
    com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse getResponse();
    /**
     * <code>optional .DiscoveryResponse response = 2;</code>
     */
    com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponseOrBuilder getResponseOrBuilder();
  }
  public interface DiscoveryRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DiscoveryRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required .OperatingSystem os = 2;</code>
     */
    boolean hasOs();
    /**
     * <code>required .OperatingSystem os = 2;</code>
     */
    com.polytech.spik.protocol.DiscoveryMessages.OperatingSystem getOs();

    /**
     * <code>required string manufacturer = 3;</code>
     */
    boolean hasManufacturer();
    /**
     * <code>required string manufacturer = 3;</code>
     */
    java.lang.String getManufacturer();
    /**
     * <code>required string manufacturer = 3;</code>
     */
    com.google.protobuf.ByteString
        getManufacturerBytes();

    /**
     * <code>required string model = 4;</code>
     */
    boolean hasModel();
    /**
     * <code>required string model = 4;</code>
     */
    java.lang.String getModel();
    /**
     * <code>required string model = 4;</code>
     */
    com.google.protobuf.ByteString
        getModelBytes();

    /**
     * <code>required int32 sdkVersion = 5;</code>
     */
    boolean hasSdkVersion();
    /**
     * <code>required int32 sdkVersion = 5;</code>
     */
    int getSdkVersion();
  }
  public interface DiscoveryResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DiscoveryResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required .OperatingSystem os = 2;</code>
     */
    boolean hasOs();
    /**
     * <code>required .OperatingSystem os = 2;</code>
     */
    com.polytech.spik.protocol.DiscoveryMessages.OperatingSystem getOs();

    /**
     * <code>required string version = 3;</code>
     */
    boolean hasVersion();
    /**
     * <code>required string version = 3;</code>
     */
    java.lang.String getVersion();
    /**
     * <code>required string version = 3;</code>
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <code>required int32 port = 4;</code>
     */
    boolean hasPort();
    /**
     * <code>required int32 port = 4;</code>
     */
    int getPort();
  }

  /**
   * Protobuf type {@code DiscoveryMessage}
   */
  public static final class DiscoveryMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:DiscoveryMessage)
      DiscoveryMessageOrBuilder {
    public static final int REQUEST_FIELD_NUMBER = 1;
    public static final int RESPONSE_FIELD_NUMBER = 2;
    private static final DiscoveryMessage defaultInstance;
    private static final long serialVersionUID = 0L;
    public static com.google.protobuf.Parser<DiscoveryMessage> PARSER =
        new com.google.protobuf.AbstractParser<DiscoveryMessage>() {
      public DiscoveryMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DiscoveryMessage(input, extensionRegistry);
      }
    };

    static {
      defaultInstance = new DiscoveryMessage(true);
      defaultInstance.initFields();
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    private int bitField0_;
    private int typeCase_ = 0;
    private java.lang.Object type_;
    private byte memoizedIsInitialized = -1;
    private int memoizedSerializedSize = -1;

    // Use DiscoveryMessage.newBuilder() to construct.
    private DiscoveryMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DiscoveryMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }
    private DiscoveryMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest.Builder subBuilder = null;
              if (typeCase_ == 1) {
                subBuilder = ((com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest) type_).toBuilder();
              }
              type_ = input.readMessage(com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest) type_);
                type_ = subBuilder.buildPartial();
              }
              typeCase_ = 1;
              break;
            }
            case 18: {
              com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse.Builder subBuilder = null;
              if (typeCase_ == 2) {
                subBuilder = ((com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse) type_).toBuilder();
              }
              type_ = input.readMessage(com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse) type_);
                type_ = subBuilder.buildPartial();
              }
              typeCase_ = 2;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static DiscoveryMessage getDefaultInstance() {
      return defaultInstance;
    };

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.polytech.spik.protocol.DiscoveryMessages.internal_static_DiscoveryMessage_descriptor;
    }

    public static com.polytech.spik.protocol.DiscoveryMessages.DiscoveryMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.polytech.spik.protocol.DiscoveryMessages.DiscoveryMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.polytech.spik.protocol.DiscoveryMessages.DiscoveryMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.polytech.spik.protocol.DiscoveryMessages.DiscoveryMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.polytech.spik.protocol.DiscoveryMessages.DiscoveryMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }

    public static com.polytech.spik.protocol.DiscoveryMessages.DiscoveryMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static com.polytech.spik.protocol.DiscoveryMessages.DiscoveryMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }

    public static com.polytech.spik.protocol.DiscoveryMessages.DiscoveryMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }

    public static com.polytech.spik.protocol.DiscoveryMessages.DiscoveryMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }

    public static com.polytech.spik.protocol.DiscoveryMessages.DiscoveryMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }

    public static Builder newBuilder(com.polytech.spik.protocol.DiscoveryMessages.DiscoveryMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }

    public DiscoveryMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.polytech.spik.protocol.DiscoveryMessages.internal_static_DiscoveryMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.polytech.spik.protocol.DiscoveryMessages.DiscoveryMessage.class, com.polytech.spik.protocol.DiscoveryMessages.DiscoveryMessage.Builder.class);
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DiscoveryMessage> getParserForType() {
      return PARSER;
    }

    public TypeCase
    getTypeCase() {
      return TypeCase.valueOf(
          typeCase_);
    }

    /**
     * <code>optional .DiscoveryRequest request = 1;</code>
     */
    public boolean hasRequest() {
      return typeCase_ == 1;
    }

    /**
     * <code>optional .DiscoveryRequest request = 1;</code>
     */
    public com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest getRequest() {
      if (typeCase_ == 1) {
         return (com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest) type_;
      }
      return com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest.getDefaultInstance();
    }

    /**
     * <code>optional .DiscoveryRequest request = 1;</code>
     */
    public com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequestOrBuilder getRequestOrBuilder() {
      if (typeCase_ == 1) {
         return (com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest) type_;
      }
      return com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest.getDefaultInstance();
    }

    /**
     * <code>optional .DiscoveryResponse response = 2;</code>
     */
    public boolean hasResponse() {
      return typeCase_ == 2;
    }

    /**
     * <code>optional .DiscoveryResponse response = 2;</code>
     */
    public com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse getResponse() {
      if (typeCase_ == 2) {
         return (com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse) type_;
      }
      return com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse.getDefaultInstance();
    }

    /**
     * <code>optional .DiscoveryResponse response = 2;</code>
     */
    public com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponseOrBuilder getResponseOrBuilder() {
      if (typeCase_ == 2) {
         return (com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse) type_;
      }
      return com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse.getDefaultInstance();
    }

    private void initFields() {
    }

    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasRequest()) {
        if (!getRequest().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasResponse()) {
        if (!getResponse().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (typeCase_ == 1) {
        output.writeMessage(1, (com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest) type_);
      }
      if (typeCase_ == 2) {
        output.writeMessage(2, (com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse) type_);
      }
      getUnknownFields().writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (typeCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest) type_);
      }
      if (typeCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse) type_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public Builder newBuilderForType() { return newBuilder(); }

    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
public enum TypeCase
        implements com.google.protobuf.Internal.EnumLite {
      REQUEST(1),
      RESPONSE(2),
      TYPE_NOT_SET(0);
      private int value = 0;
      private TypeCase(int value) {
        this.value = value;
      }
      public static TypeCase valueOf(int value) {
        switch (value) {
          case 1: return REQUEST;
          case 2: return RESPONSE;
          case 0: return TYPE_NOT_SET;
          default: throw new java.lang.IllegalArgumentException(
            "Value is undefined for this oneof enum.");
        }
      }
      public int getNumber() {
        return this.value;
      }
    }

    /**
     * Protobuf type {@code DiscoveryMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DiscoveryMessage)
        com.polytech.spik.protocol.DiscoveryMessages.DiscoveryMessageOrBuilder {
      private int typeCase_ = 0;
      private java.lang.Object type_;
      private int bitField0_;
      private com.google.protobuf.SingleFieldBuilder<
          com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest, com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest.Builder, com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequestOrBuilder> requestBuilder_;
      private com.google.protobuf.SingleFieldBuilder<
          com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse, com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse.Builder, com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponseOrBuilder> responseBuilder_;
      // Construct using com.polytech.spik.protocol.DiscoveryMessages.DiscoveryMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.polytech.spik.protocol.DiscoveryMessages.internal_static_DiscoveryMessage_descriptor;
      }

      private static Builder create() {
        return new Builder();
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.polytech.spik.protocol.DiscoveryMessages.internal_static_DiscoveryMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.polytech.spik.protocol.DiscoveryMessages.DiscoveryMessage.class, com.polytech.spik.protocol.DiscoveryMessages.DiscoveryMessage.Builder.class);
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }

      public Builder clear() {
        super.clear();
        typeCase_ = 0;
        type_ = null;
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.polytech.spik.protocol.DiscoveryMessages.internal_static_DiscoveryMessage_descriptor;
      }

      public com.polytech.spik.protocol.DiscoveryMessages.DiscoveryMessage getDefaultInstanceForType() {
        return com.polytech.spik.protocol.DiscoveryMessages.DiscoveryMessage.getDefaultInstance();
      }

      public com.polytech.spik.protocol.DiscoveryMessages.DiscoveryMessage build() {
        com.polytech.spik.protocol.DiscoveryMessages.DiscoveryMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.polytech.spik.protocol.DiscoveryMessages.DiscoveryMessage buildPartial() {
        com.polytech.spik.protocol.DiscoveryMessages.DiscoveryMessage result = new com.polytech.spik.protocol.DiscoveryMessages.DiscoveryMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (typeCase_ == 1) {
          if (requestBuilder_ == null) {
            result.type_ = type_;
          } else {
            result.type_ = requestBuilder_.build();
          }
        }
        if (typeCase_ == 2) {
          if (responseBuilder_ == null) {
            result.type_ = type_;
          } else {
            result.type_ = responseBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.typeCase_ = typeCase_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.polytech.spik.protocol.DiscoveryMessages.DiscoveryMessage) {
          return mergeFrom((com.polytech.spik.protocol.DiscoveryMessages.DiscoveryMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.polytech.spik.protocol.DiscoveryMessages.DiscoveryMessage other) {
        if (other == com.polytech.spik.protocol.DiscoveryMessages.DiscoveryMessage.getDefaultInstance()) return this;
        switch (other.getTypeCase()) {
          case REQUEST: {
            mergeRequest(other.getRequest());
            break;
          }
          case RESPONSE: {
            mergeResponse(other.getResponse());
            break;
          }
          case TYPE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (hasRequest()) {
          if (!getRequest().isInitialized()) {

            return false;
          }
        }
        if (hasResponse()) {
          if (!getResponse().isInitialized()) {

            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.polytech.spik.protocol.DiscoveryMessages.DiscoveryMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.polytech.spik.protocol.DiscoveryMessages.DiscoveryMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      public TypeCase
          getTypeCase() {
        return TypeCase.valueOf(
            typeCase_);
      }

      public Builder clearType() {
        typeCase_ = 0;
        type_ = null;
        onChanged();
        return this;
      }

      /**
       * <code>optional .DiscoveryRequest request = 1;</code>
       */
      public boolean hasRequest() {
        return typeCase_ == 1;
      }

      /**
       * <code>optional .DiscoveryRequest request = 1;</code>
       */
      public com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest getRequest() {
        if (requestBuilder_ == null) {
          if (typeCase_ == 1) {
            return (com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest) type_;
          }
          return com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest.getDefaultInstance();
        } else {
          if (typeCase_ == 1) {
            return requestBuilder_.getMessage();
          }
          return com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest.getDefaultInstance();
        }
      }

      /**
       * <code>optional .DiscoveryRequest request = 1;</code>
       */
      public Builder setRequest(
          com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest.Builder builderForValue) {
        if (requestBuilder_ == null) {
          type_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }
        typeCase_ = 1;
        return this;
      }

      /**
       * <code>optional .DiscoveryRequest request = 1;</code>
       */
      public Builder setRequest(com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          type_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }
        typeCase_ = 1;
        return this;
      }

      /**
       * <code>optional .DiscoveryRequest request = 1;</code>
       */
      public Builder mergeRequest(com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest value) {
        if (requestBuilder_ == null) {
          if (typeCase_ == 1 &&
              type_ != com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest.getDefaultInstance()) {
            type_ = com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest.newBuilder((com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest) type_)
                .mergeFrom(value).buildPartial();
          } else {
            type_ = value;
          }
          onChanged();
        } else {
          if (typeCase_ == 1) {
            requestBuilder_.mergeFrom(value);
          }
          requestBuilder_.setMessage(value);
        }
        typeCase_ = 1;
        return this;
      }

      /**
       * <code>optional .DiscoveryRequest request = 1;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          if (typeCase_ == 1) {
            typeCase_ = 0;
            type_ = null;
            onChanged();
          }
        } else {
          if (typeCase_ == 1) {
            typeCase_ = 0;
            type_ = null;
          }
          requestBuilder_.clear();
        }
        return this;
      }

      /**
       * <code>optional .DiscoveryRequest request = 1;</code>
       */
      public com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest.Builder getRequestBuilder() {
        return getRequestFieldBuilder().getBuilder();
      }

      /**
       * <code>optional .DiscoveryRequest request = 1;</code>
       */
      public com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequestOrBuilder getRequestOrBuilder() {
        if ((typeCase_ == 1) && (requestBuilder_ != null)) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          if (typeCase_ == 1) {
            return (com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest) type_;
          }
          return com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest.getDefaultInstance();
        }
      }

      /**
       * <code>optional .DiscoveryRequest request = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest, com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest.Builder, com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequestOrBuilder>
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          if (!(typeCase_ == 1)) {
            type_ = com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest.getDefaultInstance();
          }
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest, com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest.Builder, com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequestOrBuilder>(
                  (com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest) type_,
                  getParentForChildren(),
                  isClean());
          type_ = null;
        }
        typeCase_ = 1;
        return requestBuilder_;
      }

      /**
       * <code>optional .DiscoveryResponse response = 2;</code>
       */
      public boolean hasResponse() {
        return typeCase_ == 2;
      }
      /**
       * <code>optional .DiscoveryResponse response = 2;</code>
       */
      public com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse getResponse() {
        if (responseBuilder_ == null) {
          if (typeCase_ == 2) {
            return (com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse) type_;
          }
          return com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse.getDefaultInstance();
        } else {
          if (typeCase_ == 2) {
            return responseBuilder_.getMessage();
          }
          return com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse.getDefaultInstance();
        }
      }

      /**
       * <code>optional .DiscoveryResponse response = 2;</code>
       */
      public Builder setResponse(
          com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse.Builder builderForValue) {
        if (responseBuilder_ == null) {
          type_ = builderForValue.build();
          onChanged();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }
        typeCase_ = 2;
        return this;
      }

      /**
       * <code>optional .DiscoveryResponse response = 2;</code>
       */
      public Builder setResponse(com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          type_ = value;
          onChanged();
        } else {
          responseBuilder_.setMessage(value);
        }
        typeCase_ = 2;
        return this;
      }

      /**
       * <code>optional .DiscoveryResponse response = 2;</code>
       */
      public Builder mergeResponse(com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse value) {
        if (responseBuilder_ == null) {
          if (typeCase_ == 2 &&
              type_ != com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse.getDefaultInstance()) {
            type_ = com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse.newBuilder((com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse) type_)
                .mergeFrom(value).buildPartial();
          } else {
            type_ = value;
          }
          onChanged();
        } else {
          if (typeCase_ == 2) {
            responseBuilder_.mergeFrom(value);
          }
          responseBuilder_.setMessage(value);
        }
        typeCase_ = 2;
        return this;
      }
      /**
       * <code>optional .DiscoveryResponse response = 2;</code>
       */
      public Builder clearResponse() {
        if (responseBuilder_ == null) {
          if (typeCase_ == 2) {
            typeCase_ = 0;
            type_ = null;
            onChanged();
          }
        } else {
          if (typeCase_ == 2) {
            typeCase_ = 0;
            type_ = null;
          }
          responseBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .DiscoveryResponse response = 2;</code>
       */
      public com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse.Builder getResponseBuilder() {
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .DiscoveryResponse response = 2;</code>
       */
      public com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponseOrBuilder getResponseOrBuilder() {
        if ((typeCase_ == 2) && (responseBuilder_ != null)) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          if (typeCase_ == 2) {
            return (com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse) type_;
          }
          return com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse.getDefaultInstance();
        }
      }
      /**
       * <code>optional .DiscoveryResponse response = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse, com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse.Builder, com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponseOrBuilder>
          getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          if (!(typeCase_ == 2)) {
            type_ = com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse.getDefaultInstance();
          }
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse, com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse.Builder, com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponseOrBuilder>(
                  (com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse) type_,
                  getParentForChildren(),
                  isClean());
          type_ = null;
        }
        typeCase_ = 2;
        return responseBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:DiscoveryMessage)
    }

    // @@protoc_insertion_point(class_scope:DiscoveryMessage)
  }

  /**
   * Protobuf type {@code DiscoveryRequest}
   */
  public static final class DiscoveryRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:DiscoveryRequest)
      DiscoveryRequestOrBuilder {
    public static final int NAME_FIELD_NUMBER = 1;
    public static final int OS_FIELD_NUMBER = 2;
    public static final int MANUFACTURER_FIELD_NUMBER = 3;
    public static final int MODEL_FIELD_NUMBER = 4;
    public static final int SDKVERSION_FIELD_NUMBER = 5;
    private static final DiscoveryRequest defaultInstance;
    private static final long serialVersionUID = 0L;
    public static com.google.protobuf.Parser<DiscoveryRequest> PARSER =
        new com.google.protobuf.AbstractParser<DiscoveryRequest>() {
      public DiscoveryRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DiscoveryRequest(input, extensionRegistry);
      }
    };

    static {
      defaultInstance = new DiscoveryRequest(true);
      defaultInstance.initFields();
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    private int bitField0_;
    private java.lang.Object name_;
    private com.polytech.spik.protocol.DiscoveryMessages.OperatingSystem os_;
    private java.lang.Object manufacturer_;
    private java.lang.Object model_;
    private int sdkVersion_;
    private byte memoizedIsInitialized = -1;
    private int memoizedSerializedSize = -1;

    // Use DiscoveryRequest.newBuilder() to construct.
    private DiscoveryRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DiscoveryRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }
    private DiscoveryRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.polytech.spik.protocol.DiscoveryMessages.OperatingSystem value = com.polytech.spik.protocol.DiscoveryMessages.OperatingSystem.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                os_ = value;
              }
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              manufacturer_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              model_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              sdkVersion_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static DiscoveryRequest getDefaultInstance() {
      return defaultInstance;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.polytech.spik.protocol.DiscoveryMessages.internal_static_DiscoveryRequest_descriptor;
    }

    public static com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }

    public static com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }

    public static com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }

    public static com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }

    public static com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }

    public static Builder newBuilder(com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }

    public DiscoveryRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.polytech.spik.protocol.DiscoveryMessages.internal_static_DiscoveryRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest.class, com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest.Builder.class);
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DiscoveryRequest> getParserForType() {
      return PARSER;
    }

    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }

    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }

    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>required .OperatingSystem os = 2;</code>
     */
    public boolean hasOs() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }

    /**
     * <code>required .OperatingSystem os = 2;</code>
     */
    public com.polytech.spik.protocol.DiscoveryMessages.OperatingSystem getOs() {
      return os_;
    }

    /**
     * <code>required string manufacturer = 3;</code>
     */
    public boolean hasManufacturer() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }

    /**
     * <code>required string manufacturer = 3;</code>
     */
    public java.lang.String getManufacturer() {
      java.lang.Object ref = manufacturer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          manufacturer_ = s;
        }
        return s;
      }
    }

    /**
     * <code>required string manufacturer = 3;</code>
     */
    public com.google.protobuf.ByteString
        getManufacturerBytes() {
      java.lang.Object ref = manufacturer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        manufacturer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>required string model = 4;</code>
     */
    public boolean hasModel() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }

    /**
     * <code>required string model = 4;</code>
     */
    public java.lang.String getModel() {
      java.lang.Object ref = model_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          model_ = s;
        }
        return s;
      }
    }

    /**
     * <code>required string model = 4;</code>
     */
    public com.google.protobuf.ByteString
        getModelBytes() {
      java.lang.Object ref = model_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        model_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>required int32 sdkVersion = 5;</code>
     */
    public boolean hasSdkVersion() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }

    /**
     * <code>required int32 sdkVersion = 5;</code>
     */
    public int getSdkVersion() {
      return sdkVersion_;
    }

    private void initFields() {
      name_ = "";
      os_ = com.polytech.spik.protocol.DiscoveryMessages.OperatingSystem.WINDOWS;
      manufacturer_ = "";
      model_ = "";
      sdkVersion_ = 0;
    }

    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOs()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasManufacturer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasModel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSdkVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, os_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getManufacturerBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getModelBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, sdkVersion_);
      }
      getUnknownFields().writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, os_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getManufacturerBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getModelBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, sdkVersion_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public Builder newBuilderForType() { return newBuilder(); }

    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * Protobuf type {@code DiscoveryRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DiscoveryRequest)
        com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequestOrBuilder {
      private int bitField0_;
      private java.lang.Object name_ = "";
      private com.polytech.spik.protocol.DiscoveryMessages.OperatingSystem os_ = com.polytech.spik.protocol.DiscoveryMessages.OperatingSystem.WINDOWS;
      private java.lang.Object manufacturer_ = "";
      private java.lang.Object model_ = "";
      private int sdkVersion_ ;

      // Construct using com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.polytech.spik.protocol.DiscoveryMessages.internal_static_DiscoveryRequest_descriptor;
      }

      private static Builder create() {
        return new Builder();
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.polytech.spik.protocol.DiscoveryMessages.internal_static_DiscoveryRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest.class, com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest.Builder.class);
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        os_ = com.polytech.spik.protocol.DiscoveryMessages.OperatingSystem.WINDOWS;
        bitField0_ = (bitField0_ & ~0x00000002);
        manufacturer_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        model_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        sdkVersion_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.polytech.spik.protocol.DiscoveryMessages.internal_static_DiscoveryRequest_descriptor;
      }

      public com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest getDefaultInstanceForType() {
        return com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest.getDefaultInstance();
      }

      public com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest build() {
        com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest buildPartial() {
        com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest result = new com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.os_ = os_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.manufacturer_ = manufacturer_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.model_ = model_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.sdkVersion_ = sdkVersion_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest) {
          return mergeFrom((com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest other) {
        if (other == com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasOs()) {
          setOs(other.getOs());
        }
        if (other.hasManufacturer()) {
          bitField0_ |= 0x00000004;
          manufacturer_ = other.manufacturer_;
          onChanged();
        }
        if (other.hasModel()) {
          bitField0_ |= 0x00000008;
          model_ = other.model_;
          onChanged();
        }
        if (other.hasSdkVersion()) {
          setSdkVersion(other.getSdkVersion());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {

          return false;
        }
        if (!hasOs()) {

          return false;
        }
        if (!hasManufacturer()) {

          return false;
        }
        if (!hasModel()) {

          return false;
        }
        if (!hasSdkVersion()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.polytech.spik.protocol.DiscoveryMessages.DiscoveryRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }

      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }

      /**
       * <code>required .OperatingSystem os = 2;</code>
       */
      public boolean hasOs() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }

      /**
       * <code>required .OperatingSystem os = 2;</code>
       */
      public com.polytech.spik.protocol.DiscoveryMessages.OperatingSystem getOs() {
        return os_;
      }

      /**
       * <code>required .OperatingSystem os = 2;</code>
       */
      public Builder setOs(com.polytech.spik.protocol.DiscoveryMessages.OperatingSystem value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        os_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>required .OperatingSystem os = 2;</code>
       */
      public Builder clearOs() {
        bitField0_ = (bitField0_ & ~0x00000002);
        os_ = com.polytech.spik.protocol.DiscoveryMessages.OperatingSystem.WINDOWS;
        onChanged();
        return this;
      }

      /**
       * <code>required string manufacturer = 3;</code>
       */
      public boolean hasManufacturer() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }

      /**
       * <code>required string manufacturer = 3;</code>
       */
      public java.lang.String getManufacturer() {
        java.lang.Object ref = manufacturer_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            manufacturer_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>required string manufacturer = 3;</code>
       */
      public Builder setManufacturer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        manufacturer_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>required string manufacturer = 3;</code>
       */
      public com.google.protobuf.ByteString
          getManufacturerBytes() {
        java.lang.Object ref = manufacturer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          manufacturer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>required string manufacturer = 3;</code>
       */
      public Builder setManufacturerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        manufacturer_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>required string manufacturer = 3;</code>
       */
      public Builder clearManufacturer() {
        bitField0_ = (bitField0_ & ~0x00000004);
        manufacturer_ = getDefaultInstance().getManufacturer();
        onChanged();
        return this;
      }

      /**
       * <code>required string model = 4;</code>
       */
      public boolean hasModel() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }

      /**
       * <code>required string model = 4;</code>
       */
      public java.lang.String getModel() {
        java.lang.Object ref = model_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            model_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>required string model = 4;</code>
       */
      public Builder setModel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        model_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>required string model = 4;</code>
       */
      public com.google.protobuf.ByteString
          getModelBytes() {
        java.lang.Object ref = model_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          model_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>required string model = 4;</code>
       */
      public Builder setModelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        model_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>required string model = 4;</code>
       */
      public Builder clearModel() {
        bitField0_ = (bitField0_ & ~0x00000008);
        model_ = getDefaultInstance().getModel();
        onChanged();
        return this;
      }

      /**
       * <code>required int32 sdkVersion = 5;</code>
       */
      public boolean hasSdkVersion() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 sdkVersion = 5;</code>
       */
      public int getSdkVersion() {
        return sdkVersion_;
      }
      /**
       * <code>required int32 sdkVersion = 5;</code>
       */
      public Builder setSdkVersion(int value) {
        bitField0_ |= 0x00000010;
        sdkVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 sdkVersion = 5;</code>
       */
      public Builder clearSdkVersion() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sdkVersion_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:DiscoveryRequest)
    }

    // @@protoc_insertion_point(class_scope:DiscoveryRequest)
  }

  /**
   * Protobuf type {@code DiscoveryResponse}
   */
  public static final class DiscoveryResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:DiscoveryResponse)
      DiscoveryResponseOrBuilder {
    public static final int NAME_FIELD_NUMBER = 1;
    public static final int OS_FIELD_NUMBER = 2;
    public static final int VERSION_FIELD_NUMBER = 3;
    public static final int PORT_FIELD_NUMBER = 4;
    private static final DiscoveryResponse defaultInstance;
    private static final long serialVersionUID = 0L;
    public static com.google.protobuf.Parser<DiscoveryResponse> PARSER =
        new com.google.protobuf.AbstractParser<DiscoveryResponse>() {
      public DiscoveryResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DiscoveryResponse(input, extensionRegistry);
      }
    };

    static {
      defaultInstance = new DiscoveryResponse(true);
      defaultInstance.initFields();
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    private int bitField0_;
    private java.lang.Object name_;
    private com.polytech.spik.protocol.DiscoveryMessages.OperatingSystem os_;
    private java.lang.Object version_;
    private int port_;
    private byte memoizedIsInitialized = -1;
    private int memoizedSerializedSize = -1;
    // Use DiscoveryResponse.newBuilder() to construct.
    private DiscoveryResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DiscoveryResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private DiscoveryResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.polytech.spik.protocol.DiscoveryMessages.OperatingSystem value = com.polytech.spik.protocol.DiscoveryMessages.OperatingSystem.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                os_ = value;
              }
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              version_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              port_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static DiscoveryResponse getDefaultInstance() {
      return defaultInstance;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.polytech.spik.protocol.DiscoveryMessages.internal_static_DiscoveryResponse_descriptor;
    }

    public static com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }

    public static com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }

    public static com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }

    public static com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }

    public static com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }

    public static Builder newBuilder(com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }

    public DiscoveryResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.polytech.spik.protocol.DiscoveryMessages.internal_static_DiscoveryResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse.class, com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse.Builder.class);
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DiscoveryResponse> getParserForType() {
      return PARSER;
    }

    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }

    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }

    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>required .OperatingSystem os = 2;</code>
     */
    public boolean hasOs() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }

    /**
     * <code>required .OperatingSystem os = 2;</code>
     */
    public com.polytech.spik.protocol.DiscoveryMessages.OperatingSystem getOs() {
      return os_;
    }

    /**
     * <code>required string version = 3;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }

    /**
     * <code>required string version = 3;</code>
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          version_ = s;
        }
        return s;
      }
    }

    /**
     * <code>required string version = 3;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>required int32 port = 4;</code>
     */
    public boolean hasPort() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }

    /**
     * <code>required int32 port = 4;</code>
     */
    public int getPort() {
      return port_;
    }

    private void initFields() {
      name_ = "";
      os_ = com.polytech.spik.protocol.DiscoveryMessages.OperatingSystem.WINDOWS;
      version_ = "";
      port_ = 0;
    }

    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOs()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, os_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getVersionBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, port_);
      }
      getUnknownFields().writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, os_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getVersionBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, port_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public Builder newBuilderForType() { return newBuilder(); }

    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * Protobuf type {@code DiscoveryResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DiscoveryResponse)
        com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponseOrBuilder {
      private int bitField0_;
      private java.lang.Object name_ = "";
      private com.polytech.spik.protocol.DiscoveryMessages.OperatingSystem os_ = com.polytech.spik.protocol.DiscoveryMessages.OperatingSystem.WINDOWS;
      private java.lang.Object version_ = "";
      private int port_ ;
      // Construct using com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.polytech.spik.protocol.DiscoveryMessages.internal_static_DiscoveryResponse_descriptor;
      }

      private static Builder create() {
        return new Builder();
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.polytech.spik.protocol.DiscoveryMessages.internal_static_DiscoveryResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse.class, com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse.Builder.class);
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        os_ = com.polytech.spik.protocol.DiscoveryMessages.OperatingSystem.WINDOWS;
        bitField0_ = (bitField0_ & ~0x00000002);
        version_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        port_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.polytech.spik.protocol.DiscoveryMessages.internal_static_DiscoveryResponse_descriptor;
      }

      public com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse getDefaultInstanceForType() {
        return com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse.getDefaultInstance();
      }

      public com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse build() {
        com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse buildPartial() {
        com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse result = new com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.os_ = os_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.port_ = port_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse) {
          return mergeFrom((com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse other) {
        if (other == com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasOs()) {
          setOs(other.getOs());
        }
        if (other.hasVersion()) {
          bitField0_ |= 0x00000004;
          version_ = other.version_;
          onChanged();
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {

          return false;
        }
        if (!hasOs()) {

          return false;
        }
        if (!hasVersion()) {

          return false;
        }
        if (!hasPort()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.polytech.spik.protocol.DiscoveryMessages.DiscoveryResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }

      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }

      /**
       * <code>required .OperatingSystem os = 2;</code>
       */
      public boolean hasOs() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }

      /**
       * <code>required .OperatingSystem os = 2;</code>
       */
      public com.polytech.spik.protocol.DiscoveryMessages.OperatingSystem getOs() {
        return os_;
      }

      /**
       * <code>required .OperatingSystem os = 2;</code>
       */
      public Builder setOs(com.polytech.spik.protocol.DiscoveryMessages.OperatingSystem value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        os_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>required .OperatingSystem os = 2;</code>
       */
      public Builder clearOs() {
        bitField0_ = (bitField0_ & ~0x00000002);
        os_ = com.polytech.spik.protocol.DiscoveryMessages.OperatingSystem.WINDOWS;
        onChanged();
        return this;
      }

      /**
       * <code>required string version = 3;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }

      /**
       * <code>required string version = 3;</code>
       */
      public java.lang.String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            version_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>required string version = 3;</code>
       */
      public Builder setVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        version_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>required string version = 3;</code>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        java.lang.Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>required string version = 3;</code>
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        version_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>required string version = 3;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000004);
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }

      /**
       * <code>required int32 port = 4;</code>
       */
      public boolean hasPort() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 port = 4;</code>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>required int32 port = 4;</code>
       */
      public Builder setPort(int value) {
        bitField0_ |= 0x00000008;
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 port = 4;</code>
       */
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000008);
        port_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:DiscoveryResponse)
    }

    // @@protoc_insertion_point(class_scope:DiscoveryResponse)
  }

  // @@protoc_insertion_point(outer_class_scope)
}
